(define (make-account balance)
    (define (withdraw amount)
        (set! balance (- balance amount)))
    (define (deposit amount)
        (set! balance (+ balance amount)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'get-balance) balance)
            (else (error "unknown request!"))))
    dispatch)
